{{- if and .Values.backend.persistence.enabled (not .Values.backend.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delivery-platform-data
  namespace: {{ include "delivery-platform.namespace" . }}
  labels:
    {{- include "delivery-platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: delivery-platform
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
