apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-username: {{ .Values.admin.username | quote }}
  admin-password: {{ .Values.admin.password | quote }}
  listener-secret: {{ .Values.config.listenerSecret | quote }}
  {{- if .Values.postgres.enabled }}
  postgres-username: {{ .Values.postgres.username | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
  postgres-database: {{ .Values.postgres.database | quote }}
  {{- end }}
