apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab.fullname" . }}-root
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.rootPassword | quote }}
