apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependency-track.fullname" . }}-apiserver
  labels:
    {{- include "dependency-track.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiServer.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.apiServer.nodePort }}
      nodePort: {{ .Values.service.apiServer.nodePort }}
      {{- end }}
  selector:
    {{- include "dependency-track.selectorLabels" . | nindent 4 }}
---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependency-track.fullname" . }}-frontend
  labels:
    {{- include "dependency-track.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.frontend.nodePort }}
      nodePort: {{ .Values.service.frontend.nodePort }}
      {{- end }}
  selector:
    {{- include "dependency-track.frontendSelectorLabels" . | nindent 4 }}
{{- end }}