# 基于 openjdk:23 镜像
FROM node:20-bullseye-slim

USER root

# 设置环境变量，避免交互提示
ENV DEBIAN_FRONTEND=noninteractive

RUN echo "当前基础镜像的操作系统信息：" && cat /etc/os-release

# 更新包列表并安装必要的依赖
RUN apt-get update && \
    apt-get install -y \
        git \
        jq \
        ca-certificates \
        curl \
        wget \
        unzip \
        tar \
        gnupg \
        lsb-release && \
    # 添加 Docker 的官方 GPG 密钥
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    # 设置 Docker 仓库
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    # 更新包列表
    apt-get update && \
    # 安装 Docker 相关包
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin && \
    # 清理 apt 缓存
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN node -v

# 修改依赖源
RUN npm config set registry https//registry.npm.taobao.org

# 恢复默认环境变量
ENV DEBIAN_FRONTEND=dialog
    