{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops.fullname" . }}-jwt
  labels:
    {{- include "devops.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  secret: {{ .Values.backend.config.jwtSecret | b64enc | quote }}
{{- end }}