{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops.fullname" . }}-backend
  labels:
    {{- include "devops.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.backend.config.springProfilesActive | quote }}
  SERVER_PORT: {{ .Values.backend.config.serverPort | quote }}
  USER_JWT_EXPIRE_SECONDS: {{ .Values.backend.config.jwtExpireSeconds | quote }}
  DOCGEN_SCRIPT_PATH: {{ .Values.backend.config.docgenScriptPath | quote }}
  DOCGEN_PYTHON_PATH: {{ .Values.backend.config.docgenPythonPath | quote }}
  DOCGEN_OUTPUT_DIR: {{ .Values.backend.config.docgenOutputDir | quote }}
{{- end }}