server:
  port: 3000

spring:
  application:
    name: devops-base
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
debug: false
