apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  USER_JWT_EXPIRE_SECONDS: {{ .Values.config.jwtExpireSeconds | quote }}
  DOCGEN_SCRIPT_PATH: {{ .Values.config.docgenScriptPath | quote }}
  DOCGEN_PYTHON_PATH: {{ .Values.config.docgenPythonPath | quote }}
  DOCGEN_OUTPUT_DIR: {{ .Values.config.docgenOutputDir | quote }}
  SPRING_DATASOURCE_URL: "jdbc:sqlite:{{ .Values.persistence.mountPath }}/hfwas-devops.db"
  LOGGING_CONFIG: "file:{{ .Values.config.logbackPath | default "/app/config/logback-spring.xml" }}"