name: CI

on:
  push:
    paths:
      - 'deploy/opensumi/**'
      - '.github//workflows/opensumi.yml'

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
        ci-project: [node, jsdom]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          yarn install --immutable
          yarn constraints

      - name: CI
        run: |
          yarn run ci --selectProjects ${{ matrix.ci-project }}